### ISSUE TITLE
Miner reports invalid messages after short period of time

### ISSUE THREAD

**Issue by caspiano** [Axentro/Axentro#381]
## Checklist
- [x] You've tried with the latest version of Axentro
- [x] You've confirmed this issue is not a duplicate

## Description

I've been trying out the Axentro miner and after an average of 45 minutes, I start getting these messages until I stop getting any logs at all 

```shell[ 2021-01-20 00:43:54 --    Info ] 100 works, 14 [Work/s]
[ 2021-01-20 00:44:01 --    Info ] PREPARING NEXT SLOW BLOCK: 66390 at approximate difficulty: 29
[ 2021-01-20 00:44:01 --    Warn ] receive invalid message, will be ignored
[ 2021-01-20 00:45:50 --    Info ] PREPARING NEXT SLOW BLOCK: 66392 at approximate difficulty: 29
[ 2021-01-20 00:45:50 --    Warn ] receive invalid message, will be ignored
```

## Environment

- Using docker: no
- Crystal 0.35.1 (2020-06-19)
- LLVM: 9.0.1
- Default target: x86_64-apple-macosx
- Which environment? http://mainnet.axentro.io

## Command Lines and results

```bash
./bin/axem -w mainnet-0.json -n http://mainnet.axentro.io --process=5 --password='<redacted>'
```

**Comment by kingsleyh** [comment]
Thanks will investigate - could you also try the minaxnt miner and see how that performs for you
