### ISSUE TITLE
Share "official" nodes to connect to mainnet

### ISSUE THREAD

**Issue by q9f** [Axentro/Axentro#389]
## Checklist
- [x] You've checked that this feature is not already implemented
- [x] You've confirmed that this is not a duplicate request

## Description
It's currently not possible to run a node on an _official_ network without knowing _official_ nodes.

```
[ 2021-02-16 10:32:17 --    Warn ] no connecting node has been specified
[ 2021-02-16 10:32:17 --    Warn ] so this node is standalone from other network
```

Please, share official nodes or add them to the node.

**Comment by kingsleyh** [comment]
Connecting a public node is currently restricted because we still need to make more improvements before we can support many nodes running. But you can connect a private node still. The only node available for connection is currently:   http://mainnet.axentro.io

—Kingsley

**Comment by q9f** [comment]
So you get 25% of all rewards because you are the only public node to main with?

**Comment by kingsleyh** [comment]
Currently yes.

—Kingsley

**Comment by kingsleyh** [comment]
will improve in the future and hopefully be able to re-enable nodes
